
package com.main.view;

import com.main.control.OmniActionListener;
import com.main.control.MainTableSelectionListener;
import com.main.model.MainHeaderHandler;
import com.main.model.HeaderTableEngine;
import com.main.model.MainLineHandler;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;

public class GUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceFrame
     */
    public GUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSP1 = new javax.swing.JScrollPane();
        invoiceHTable = new javax.swing.JTable();
        createInvoiceBtn = new javax.swing.JButton();
        deleteInvoiceBtn = new javax.swing.JButton();
        jLbl1 = new javax.swing.JLabel();
        jLbl2 = new javax.swing.JLabel();
        jLbl3 = new javax.swing.JLabel();
        jLbl4 = new javax.swing.JLabel();
        cstNameLbl = new javax.swing.JLabel();
        invoiceDateLabel = new javax.swing.JLabel();
        invoiceNumberLabel = new javax.swing.JLabel();
        invoiceTotalIabel = new javax.swing.JLabel();
        jSP2 = new javax.swing.JScrollPane();
        invoiceLTable = new javax.swing.JTable();
        createLineBtn = new javax.swing.JButton();
        deleteLineBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMB1 = new javax.swing.JMenuBar();
        jMnu1 = new javax.swing.JMenu();
        loadMItem = new javax.swing.JMenuItem();
        saveMItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoiceHTable.setBackground(new java.awt.Color(153, 204, 255));
        invoiceHTable.setForeground(new java.awt.Color(102, 102, 255));
        invoiceHTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        invoiceHTable.getSelectionModel().addListSelectionListener(selectionListener);
        jSP1.setViewportView(invoiceHTable);

        createInvoiceBtn.setText("New Invoice");
        createInvoiceBtn.addActionListener(actionListener);
        createInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createInvoiceBtnActionPerformed(evt);
            }
        });

        deleteInvoiceBtn.setText("Delete Invoice");
        deleteInvoiceBtn.addActionListener(actionListener);

        jLbl1.setText("Invoice Number");

        jLbl2.setText("Invoice Date");

        jLbl3.setText("Customer Name");

        jLbl4.setText("Invoice Total");

        invoiceLTable.setBackground(new java.awt.Color(204, 204, 255));
        invoiceLTable.setForeground(new java.awt.Color(51, 51, 255));
        invoiceLTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jSP2.setViewportView(invoiceLTable);

        createLineBtn.setText("New Line");
        createLineBtn.addActionListener(actionListener);

        deleteLineBtn.setText("Delete Line");
        deleteLineBtn.addActionListener(actionListener);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sales Invoice Generator");

        jMnu1.setText("File");

        loadMItem.setText("Load Files");
        loadMItem.addActionListener(actionListener);
        jMnu1.add(loadMItem);

        saveMItem.setText("Save Files");
        saveMItem.addActionListener(actionListener);
        jMnu1.add(saveMItem);

        jMB1.add(jMnu1);

        setJMenuBar(jMB1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLbl3)
                                            .addComponent(jLbl4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(invoiceTotalIabel)
                                            .addComponent(invoiceNumberLabel)
                                            .addComponent(invoiceDateLabel)
                                            .addComponent(cstNameLbl)))
                                    .addComponent(jLbl2)
                                    .addComponent(jLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(159, 159, 159)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSP2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(createInvoiceBtn)
                        .addGap(89, 89, 89)
                        .addComponent(deleteInvoiceBtn)
                        .addGap(137, 137, 137)
                        .addComponent(createLineBtn)
                        .addGap(132, 132, 132)
                        .addComponent(deleteLineBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLbl4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(26, 26, 26)
                                                    .addComponent(invoiceNumberLabel)
                                                    .addGap(23, 23, 23)
                                                    .addComponent(invoiceDateLabel))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLbl1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLbl2)))
                                            .addGap(23, 23, 23)
                                            .addComponent(cstNameLbl))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(49, 49, 49)
                                            .addComponent(jLbl3)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(invoiceTotalIabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createInvoiceBtn)
                    .addComponent(deleteInvoiceBtn)
                    .addComponent(createLineBtn)
                    .addComponent(deleteLineBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createInvoiceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createInvoiceBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createInvoiceBtn;
    private javax.swing.JButton createLineBtn;
    private javax.swing.JLabel cstNameLbl;
    private javax.swing.JButton deleteInvoiceBtn;
    private javax.swing.JButton deleteLineBtn;
    private javax.swing.JLabel invoiceDateLabel;
    private javax.swing.JTable invoiceHTable;
    private javax.swing.JTable invoiceLTable;
    private javax.swing.JLabel invoiceNumberLabel;
    private javax.swing.JLabel invoiceTotalIabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbl1;
    private javax.swing.JLabel jLbl2;
    private javax.swing.JLabel jLbl3;
    private javax.swing.JLabel jLbl4;
    private javax.swing.JMenuBar jMB1;
    private javax.swing.JMenu jMnu1;
    private javax.swing.JScrollPane jSP1;
    private javax.swing.JScrollPane jSP2;
    private javax.swing.JMenuItem loadMItem;
    private javax.swing.JMenuItem saveMItem;
    // End of variables declaration//GEN-END:variables
    private OmniActionListener actionListener = new OmniActionListener(this);
    private ArrayList<MainHeaderHandler> invoicesArray;
    private ArrayList<MainLineHandler> linesArray;
    private HeaderTableEngine headerTableModel;
    public static SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    private MainTableSelectionListener selectionListener = new MainTableSelectionListener(this);

    public ArrayList<MainLineHandler> getLinesArray() {
        return linesArray;
    }

    public void setLinesArray(ArrayList<MainLineHandler> linesArray) {
        this.linesArray = linesArray;
    }
    
    public void setInvoicesArray(ArrayList<MainHeaderHandler> invoicesArray) {
        this.invoicesArray = invoicesArray;
    }

    public ArrayList<MainHeaderHandler> getInvoicesArray() {
        return invoicesArray;
    }
    
    public MainHeaderHandler getInvObject(int code) {
        for (MainHeaderHandler inv : invoicesArray) {
            if (inv.getNumber() == code) {
                return inv;
            }
        }
        return null;
    }

    public HeaderTableEngine getHeaderTableModel() {
        return headerTableModel;
    }

    public void setHeaderTableModel(HeaderTableEngine headerTableModel) {
        this.headerTableModel = headerTableModel;
    }

    public JTable getInvoiceHTable() {
        return invoiceHTable;
    }

    public JTable getInvoiceLTable() {
        return invoiceLTable;
    }

    public JLabel getCstNameLbl() {
        return cstNameLbl;
    }

    public JLabel getInvoiceDateLabel() {
        return invoiceDateLabel;
    }

    public JLabel getInvoiceNumberLabel() {
        return invoiceNumberLabel;
    }

    public JLabel getInvoiceTotalIabel() {
        return invoiceTotalIabel;
    }

    public OmniActionListener getActionListener() {
        return actionListener;
    }
    
    
}
